### ISSUE TITLE
noTunes... or noJunkApps?

### ISSUE THREAD

**Issue by rnkn** [tombonez/noTunes#12]
First I'd like to echo the majority of closed issues just saying thank you for creating this.

Have you considered extending this app (or making a different app) to prevent a selection of the built-in junk apps, e.g. Books, Photos, News, etc.? Maybe as like a dropdown menu with checkboxes?

Thanks again for your work. This is a must-have.

**Comment by tombonez** [comment]
Hi @rnkn,

No problem, I'm glad you're finding my small utility useful 🙂

I did with the launch of Apple Music consider creating a new app that'd allow users to add apps to the blocked list, but I just haven't found time to revisit that idea.

I've added this issue to my personal todo list, so if/when I get around to it I'll let you know.

Cheers,
Tom 👍

**Comment by rnkn** [comment]
👍
