### ISSUE TITLE
Run on startup

### ISSUE THREAD

**Issue by tsamfetch** [tombonez/noTunes#13]
Love the app, makes my life easier.

How would I go about running this on startup? 

Asking as not a power user. I know if it was in the dock then I could add it to startup items by right clicking.

**Comment by tsamfetch** [comment]
![image](https://user-images.githubusercontent.com/89933184/132045684-85b292c2-247b-4c70-af2b-a8c278415213.png)
NVM, answered my own question with this screenshot
**System Preferences > Users & Groups > Login Items**

**Comment by njudd** [comment]
I don't have access to my 'User & Groups', is there another solution to this? 
maybe with a script

thanks for your help

**Comment by tombonez** [comment]
Hi @njudd,

When you set an app to launch on startup from within an apps preferences does it work?

I assume it does, but thought I'd check before re-adding this functionality.

I originally had this functionality within the app, but removed it as it seemed unnecessary and I wasn't sure if it was even working correctly, but looks like you've given me a reason to re-add it 😄

Cheers,
Tom 🙂

**Comment by njudd** [comment]
I am locked out of "User & Groups", unrelated to your app so I can't check. 

I was wondering if there was another way to accomplish the same goal since my work does not allow me to edit that area of preferences. It's no worries if it is too much hassle, the app works amazing by the way!

**Comment by tombonez** [comment]
@njudd

Do you have any apps that have a built in "launch on startup" option?

If so, does that functionality work?

**Comment by gsingh93** [comment]
@tombonez I have a number of apps that have a setting that lets them launch on startup. AltTab, Rectangle, and Aflred are a few that I use. When you enable that preference for those apps, they automatically add themselves to Login Items (that preference is no located in "General -> Login Items and Extensions". It'd be convenient to have this preference in the app, but for now I've manually added it to the login items.
