### ISSUE TITLE
Stop VoiceOver

### ISSUE THREAD

**Issue by chengjk** [tombonez/noTunes#14]
what about VoiceOver?  no way to close hotkey( COMMOND+F5), it conflict with IDEA.

**Comment by tombonez** [comment]
Hi @chengjk 👋

Are you just after globally disabling VoiceOver?

If so, this can be done via System Preferences too, as seen [here](https://www.lifewire.com/turn-off-voiceover-on-macos-4178456).

Hopefully this solves your problems.

Cheers,
Tom 🙂

**Comment by chengjk** [comment]
it's useful, thanks a lot. 😊
