### ISSUE TITLE
Let folks find this lifesaver via Brew package as well

### ISSUE THREAD

**Issue by BaluErtl** [tombonez/noTunes#15]
I found this truly working solution referred from [Reddit](https://www.reddit.com/r/MacOS/comments/m7d75t/how_to_removedisable_musicapp_in_big_sur/), and I'm so glad that you created it, thank you so much!

It would be ultimately cool if a [Brew](https://brew.sh/) package would be also available to install this little lifesaver from wouldn't be?

**Comment by tombonez** [comment]
Hi @BaluErtl 👋

No problem at all, thanks for the kind words, appreciate it 🙂

Great suggestion!

Back when I started this small project I did look at adding the app to Homebrew (as a user myself) but one of the reasons for an app being rejected is `An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars)`.

I'd guess the project is now above that threshold, but one thing I'd like todo before submitting it is to combine the two builds of the app (add a hide menu bar icon option to the menu bar version), so it'll be as simple as `brew install --cask notunes` to install.

This shouldn't take long to add (I'll aim to get this sorted over the weekend) and then fingers crossed the app gets approved 🤞

Cheers,
Tom 🙂

**Comment by tombonez** [comment]
Hi @BaluErtl 👋

I've just now submit the noTunes [pull request](https://github.com/Homebrew/homebrew-cask/pull/111462) to the homebrew-cask repository.

Fingers crossed I've done everything correctly and it gets approved 🤞

Cheers,
Tom 🙂

**Comment by tombonez** [comment]
Hi @BaluErtl 👋

This is now live and can be installed with `brew install --cask notunes ` 😃

Cheers,
Tom 🙂

**Comment by BaluErtl** [comment]
@tombonez thanks for the swift reply & action! Now I reinstalled via Brew, works like a charm! 🙏🏼
