### ISSUE TITLE
Thank you <3

### ISSUE THREAD

**Issue by lundstrj** [tombonez/noTunes#16]
Sorry to make an issue for it but I wanted to reach out in someway and say thanks.

**Comment by tombonez** [comment]
Hi @lundstrj 👋

No problem at all, I'm glad you're finding my small utility useful 😃

Cheers,
Tom 🙂

**Comment by debaraj-barua** [comment]
Thanks @tombonez! This is a really helpful tool :D #nomorejunkapps

I am so happy I no longer have to close the pop-up window of this spammy piece of garbage in the middle of my work. 🥂

**Comment by peterldowns** [comment]
Adding to this, thank you so much for notunes. It works as expected, the documentation is good, and I can install it with homebrew. Really appreciate the hard work and effort to develop and maintain it!
