### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by salmanulfarzy** [tombonez/noTunes#2]
Hey @tombonez I just wanted to thank you for creating this. It drives me crazy when iTunes launches  unexpectedly. Thank you.

**Comment by tombonez** [comment]
Hi @salmanulfarzy! Only just received an email for this (sorry) 😕

Thanks for the kinda words, I really appreciate it 😃

iTunes unexpectedly opening up drives me crazy too 😂

**Comment by ms88privat** [comment]
I'm so glad. Itunes is just THE ultimate bad user experience ever. How can a company with so much cash not fix this.

My new HomePod tries to open Itunes, which itself will open multiple confirmation popups (age, appropriate content, ....), when I try to adjust the volume and I slightly miss-click it...

**Comment by wmhilton** [comment]
Thank you @tombonez ! I've tried everything, and this is the first thing that stops Apple Music from opening every time my bluetooth headphones connect.
