### ISSUE TITLE
monterey issues

### ISSUE THREAD

**Issue by cybacolt** [tombonez/noTunes#20]
installs from brew successfully, but does not show menu icon, or appear the defaults if you try to restore/find it.

I'm running Monterey 12.1 on a 2018 mac book pro.

let me know if theres any testing i can do to help diagnose this.

**Comment by cybacolt** [comment]
currently resorting to treating the symptom like this:
https://www.reddit.com/r/MacOS/comments/m7d75t/how_to_removedisable_musicapp_in_big_sur/#t1_hl1gs68

**Comment by tombonez** [comment]
Hi @cybacolt 👋

Strange, it's working on macOS 12.1 with a clean install for me.

The certificate is expiring within 30 days though (#21), so maybe it's linked to that, would seem odd for Apple to stop the app from running before the certificate has actually expired though.

A couple things to check whilst I update the apps certificate though:
- Is noTunes showing up in Activity Monitor?
- If so, does the following file exist `~/Library/Preferences/digital.twisted.noTunes.plist`.
- If so, quit noTunes from Activity Monitor, run `defaults delete digital.twisted.noTunes` in Terminal and relaunch noTunes.

Cheers,
Tom 🙂

**Comment by cybacolt** [comment]
Hi Tom!

looks like i just had to run the app directly - sorry, i expected it started as a service automatically after install.

thanks for the help tho!
