### ISSUE TITLE
Blocking Music only?

### ISSUE THREAD

**Issue by Dxncxn** [tombonez/noTunes#25]
Hey @tombonez,

I'd potentially be very interested in a version of noTunes which blocked the Music app but *not* iTunes (and would absolutely be happy to discuss payment for your time on this). If you'd have any interest in that, then let me know how best we could talk privately.

Thanks very much,
Duncan

**Comment by D99-1** [comment]
@Dxncxn I've had a quick look at the code and it seems do-able, just message me if you still need it and i'd be happy to get it done

**Comment by Dxncxn** [comment]
Thanks for getting in touch, @D99-1, and yes, I'm definitely still interested! What do we do now, in that case? What would be the best way for me to contact you privately?
Thanks again

**Comment by D99-1** [comment]
@Dxncxn ok but you can't just private message on github, but first I want you to try something. Open up the xcode project in xocde and view the main file, look for whereever it says iTunes and just remove that bit. That should be your fix, I would do it for you but my mac doesn't have iTunes so I can't test.

**Comment by tombonez** [comment]
@Dxncxn Do you just want the latest version of noTunes without iTunes being blocked? If so, I'll just do that now for you and share it here so anyone can use it.

**Comment by D99-1** [comment]
@Dxncxn no I'm just helping you out on how to achieve what you want, noitunes that does not block itunes

**Comment by tombonez** [comment]
> @Dxncxn Do you just want the latest version of noTunes without iTunes being blocked? If so, I'll just do that now for you and share it here so anyone can use it.

@Dxncxn If the above is correct, here you go 👍

[noTunes-3.3-only-music.zip](https://github.com/tombonez/noTunes/files/9543571/noTunes-3.3-only-music.zip)

Let me know how you get on.

**Comment by D99-1** [comment]
> > @Dxncxn Do you just want the latest version of noTunes without iTunes being blocked? If so, I'll just do that now for you and share it here so anyone can use it.
> 
> @Dxncxn If the above is correct, here you go 👍
> 
> [noTunes-3.3-only-music.zip](https://github.com/tombonez/noTunes/files/9543571/noTunes-3.3-only-music.zip)
> 
> Let me know how you get on.

.......
I never needed it, those were instructions to help you with what you needed

> Hey @tombonez,
> 
> I'd potentially be very interested in a version of noTunes which blocked the Music app but _not_ iTunes (and would absolutely be happy to discuss payment for your time on this). If you'd have any interest in that, then let me know how best we could talk privately.
> 
> Thanks very much, Duncan

**Comment by tombonez** [comment]
@D99-1 I'm responding to @Dxncxn on the issue he opened.

**Comment by D99-1** [comment]
> @D99-1 I'm responding to @Dxncxn on the issue he opened.

💀 oh no, I just realised u weren't the OP, sorry, ignore whatever I sent above

**Comment by tombonez** [comment]
@D99-1 Haha, no problem at all, appreciate you helping out 🙂

**Comment by Dxncxn** [comment]
Thanks, both (not just for your help, but also for the very entertaining little mistaken-identity skit above 😆).

Happy to confirm that this new version does exactly what it's supposed to. Whether that fact will allow me to solve my underlying problem will have to wait until I can do some more research – but clearly that's not either of your problem. 

(Although, if it DOES, it will change my life immeasurably for the better, and I will reappear here trying to throw money at you, @tombonez. But until such a time...)

Thanks again!

**Comment by tombonez** [comment]
Good to hear @Dxncxn, hopefully it solves your problem 🙂

If it does, hopefully I'll have setup my GitHub Sponsor page by then 😄
