### ISSUE TITLE
brew install fails

### ISSUE THREAD

**Issue by farmerbean** [tombonez/noTunes#28]
brew install notunes fails with:

```
Error: SHA256 mismatch
Expected: 0ad78b0a7bb2e0bb724f0de65107d5397c5a32e1d974f7b3533acc8a0dd129e7
 Actual: a74cb21de2c5b872e95422414abd1017d8f5a69dccc528e3c2d41cae97d582e8

xxx
To retry an incomplete download, remove the file above.
```

brew 3.4.6
macOS Monterey 12.3.1

**Comment by pcjmfranken** [comment]
Not using Homebrew myself but a manual download checks out:

```sh
curl -fsSLO "https://github.com/tombonez/noTunes/releases/download/v3.2/noTunes-3.2.zip"
echo "0ad78b0a7bb2e0bb724f0de65107d5397c5a32e1d974f7b3533acc8a0dd129e7  noTunes-3.2.zip" | shasum -a 256 --check

noTunes-3.2.zip: OK # output
```

**Comment by pcjmfranken** [comment]
Sigh, well, someone up the chain must think their games are worth your time 😝 

If you can confirm it really is them and you still want to verify, perhaps there's a way to automatically fetch their post-scan checksum.

**Comment by farmerbean** [comment]
My bestie from Corporate Security is online and has sorted me out - thanks for :rubber_duck: with me @pcjmfranken
