### ISSUE TITLE
Update for MacOS Catalina

### ISSUE THREAD

**Issue by elstgav** [tombonez/noTunes#3]
Catalina removed iTunes to create the new “Music” app—can this be updated to block that as well?

**Comment by tombonez** [comment]
Hi @elstgav 

No problem at all, once Xcode is re-installed I'll get this updated.

Quick question, now that the [iDevice interface is integrated into Finder](https://www.imore.com/how-sync-your-iphone-and-ipad-your-mac-macos-catalina), can you think of any reason to keep the menu bar icon? It's basically the only reason I added it and I can't think of a reason to keep it, launching the app at startup can then just be set in user preferences.

If you'd prefer the menu bar to be kept I'll just leave everything as is 👍

Cheers,
Tom :)

**Comment by elstgav** [comment]
Hey Tom,

The menu bar isn’t a concern—it’d be nice if the app can run without it. I mainly use the app to prevent iTunes/Music from launching when the play/pause button is pressed. I have headphones that connect to my phone and laptop, and pressing play will usually control the phone. But sometimes it gets confused and tries to activate my computer, which gets annoying with iTunes launching.

Thanks!

Gavin

**Comment by tombonez** [comment]
Hi @elstgav 

No problem at all :)

I've uploaded a pre-released version of the app in [releases](https://github.com/tombonez/noTunes/releases/tag/v2.0).

Everything should work as expected, the app just currently doesn't support launching on startup (this can be added manually via user preferences if needed) or hiding the menu bar icon (I'll probably just release two versions of the app).

I should find time this evening to finish things up and I'll let you know once updated so you can hide that pesky menu bar icon ;P

Any issues just let me know.

Cheers,
Tom :)

**Comment by elstgav** [comment]
Thanks Tom, works like a charm! Look forward to the no-menubar release 👍

**Comment by JacksonMaxfield** [comment]
Just wanted to say thanks for this update as well! :)

**Comment by elstgav** [comment]
@tombonez Any update on removing the menubar icon?

**Comment by tombonez** [comment]
> Just wanted to say thanks for this update as well! :)

Thanks @JacksonMaxfield appreciate it 🙂

> @tombonez Any update on removing the menubar icon?

Sorry for the wait, I was hoping to find time todo this properly (one single app with ability to hide the menu bar icon), but found myself with little.

For the time being I've compiled a separate version without the menu bar icon, it can be found in [releases](https://github.com/tombonez/noTunes/releases/tag/v2.0).

Any issues just let me know 🙂

**Comment by BKmetoff** [comment]
@tombonez hey Tom, big thanks for the effort! :) :)

**Comment by elstgav** [comment]
Thanks @tombonez, I appreciate you spending your spare time on this!

**Comment by ChrBach** [comment]
Hey Tom, thanks for this, really appreciate it!

**Comment by Bryan88418** [comment]
Howdy Tom, thank you SO MUCH for making this... it's a real headache cure!

How do you open iTunes with the NoMenu version?

**Comment by tombonez** [comment]
Thanks for the awesome comments everyone, really appreciate it!

> Howdy Tom, thank you SO MUCH for making this... it's a real headache cure!
> 
> How do you open iTunes with the NoMenu version?

Hi @Bryan88418 

You'll need to quit noTunes for iTunes to be opened when using the no menu bar icon version.

As there is no UI in this version, you'll either need to use Activity Monitor to find and quit the app or use the following command in terminal:
`osascript -e 'quit app "noTunes"'`

Cheers,
Tom :)

**Comment by BitProcessor** [comment]
Just perfect - got really annoyed by the Music.app starting on certain bluetooth events and found this via a comment somewhere. Thanks! 👍
