### ISSUE TITLE
Can't hide menu bar icon

### ISSUE THREAD

**Issue by ghost** [tombonez/noTunes#31]
Great tool.

Disabling the menu bar icon doesn't work for me, unfortunately. If I perform a right-click, it has the same effect as a left-click. The menu doesn't show up.

Tried it on Monterey & High Sierra.

Modifying the property list is not an option because it's not being created on both systems.

A good workaround for me would be to just use an older version which has no menu bar icon. It's not an option, though, because of the expired certificate. Is there a way to replace it manually with the one from 3.2+?

Edit:
I'm using a trackpad, not a mouse. If I enable the "secondary click" (two fingers), I'm able to open the menu. I'm also able to hide the icon that way on Monterey (not on High Sierra). Apparently, the right-click using command and the right-click using two-fingers create different signals.

**Comment by lfgcampos** [comment]
It would also be nice to enable the `option+click` i.o. the right click for mouse pad users!

**Comment by arnaudbouffard** [comment]
Another type of the same issue here (Catalina):
can right click icon, but left clicking on "Hide icon" doesn't hide it.

**Comment by joriswitteman** [comment]
Right clicking the icon and choosing Hide Icon works for me on macOS Monterey 12.6.1, as well as on macOS Ventura 13.0.

Very grateful for this app!

**Comment by maurymarkowitz** [comment]
Yeah, working here on Monterey 12.6.
