### ISSUE TITLE
Can sponsorship be toggled on for this repo?

### ISSUE THREAD

**Issue by extempl** [tombonez/noTunes#38]

**Comment by ipince** [comment]
I just came here to say THANKS. Apple Music's auto-launching behavior has been a nuisance to me for years, and finally there's a cure.  Thanks! <3

**Comment by tombonez** [comment]
@extempl Thanks for opening this issue. After well over a year and almost 100k downloads of noTunes, I've finally added the ability to sponsor me. No money is necessary but greatly appreciated 🙂
