### ISSUE TITLE
Music occasionally launches on Ventura 13.5.2

### ISSUE THREAD

**Issue by kerneljake** [tombonez/noTunes#41]
After a recent upgrade to 13.5.2 (22G91), Apple Music will still launch occasionally.  Most of the time I get the suppressed "dock bounce", but sometimes Music will launch fully.

**Comment by openhoangnc** [comment]
@kerneljake, you might want to try this: https://github.com/openhoangnc/NoMacMusic 
I've been using it on macOS 13 for a while, and the Music app has never launched.

**Comment by tombonez** [comment]
@kerneljake A new version push been pushed to the repo if you'd like to give it a go (Homebrew version coming shortly). Please let me know how you get on.

**Comment by bmarinov** [comment]
> @kerneljake A new version has been pushed to the repo if you'd like to give it a go (Homebrew version coming shortly). Please let me know how you get on.

Somehow I was running an old version (3.3) and just experienced the issue. Updated to 3.4 now, will report if I experience the problem again :) thanks for the update!

**Comment by kerneljake** [comment]
Things are running well for me with the new version.  Feel free to close this issue.
