### ISSUE TITLE
Cannot install version 3.4 on Mac running Sonoma 14.0 ("unknown or unsupported macOS version")

### ISSUE THREAD

**Issue by CaryInVictoria** [tombonez/noTunes#44]
(base) ➜  ~ brew install --cask notunes
/usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:33:in `block in from_symbol': unknown or unsupported macOS version: :dunno (MacOSVersionError)
...from /usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:33:in `fetch...

**Comment by tombonez** [comment]
Hi @CaryInVictoria

This is a Homebrew error with running an outdated version.

Running `brew update` should solve that for you 👍🏻
