### ISSUE TITLE
Pass file to replacement application?

### ISSUE THREAD

**Issue by mumiemonstret** [tombonez/noTunes#45]
By running the command below I managed to get Notunes to open my preferred app, Adobe Audition, instead of Apple Music when I doubleclick .wav and .mp3 files. But Audition doesn't actually open the file.

defaults write digital.twisted.noTunes replacement /Applications/Adobe\ Audition\ 2024/Adobe\ Audition\ 2024.app

**Comment by tombonez** [comment]
Hi @mumiemonstret 👋🏻

I would recommend following the guide below for updating the default app for specified file types:
https://www.tomsguide.com/how-to/how-to-set-default-apps-on-mac
