### ISSUE TITLE
Feature Request: Options to prevent the auto-opening of AppleStore

### ISSUE THREAD

**Issue by douglasjunior** [tombonez/noTunes#46]
Firstly, thank you for the app, it's fantastic!

A feature that would be fantastic would be to prevent the AppleStore from opening when we access URLs such as: https://apps.apple.com/br/app/uniprime/id1103400481

Thanks!

**Comment by heubergen** [comment]
Try https://github.com/lapcat/StopTheMacAppStore

**Comment by tombonez** [comment]
Hi @douglasjunior 👋🏻

As others have suggested, I'd recommend tackling this issue via a browser extension as it'd still allow you to open the App Store manually.
