### ISSUE TITLE
Fn keys are only partially working after installing noTunes and changing the default to spotify

### ISSUE THREAD

**Issue by mearleycf** [tombonez/noTunes#47]
I installed noTunes. I ran defaults write digital.twisted.noTunes replacement /Applications/Spotify.app. After I ran that, I also ran osascript -e 'quit app "noTunes"' and then re-opened noTunes just to make sure my defaults change was applied. 
The problem I'm having is that the f8 (play) button on my keyboard does correctly toggle over to the Spotify app now, instead of launching iTunes. But that's all it does. If I hit the button again to play music, nothing happens. In fact, none of the function controls (previous track, next track, play) work anymore. 
This is true for both my Apple Magic Keyboard and also for my Keychron K4 Pro. Same behavior.

**Comment by BtM909** [comment]
Isn't the problem that you still need to activate the app (to play something manually) in order for the control buttons to work?

**Comment by tombonez** [comment]
Hi @mearleycf 👋🏻

noTunes doesn't hijack or listen to any keyboard interactions at all, so I'd recommend making sure it works when noTunes is closed or seeing if something else is taking over the keys (e.g. a Chromium based web browser).

If you use a Chromium based web browser, I'd recommend, for example, disabling **Hardware Media Key Handling** at ﻿`chrome://flags/#hardware-media-key-handling`.

Let me know how you get on, happy to help 👍🏻
