### ISSUE TITLE
Open Spotify (or other music player) instead?

### ISSUE THREAD

**Issue by bshaffer** [tombonez/noTunes#49]
I'm shocked this isn't some optional already in MacOSX (or maybe it is?)

I'd LOVE to be able to open Spotify, or change the default somehow, instead of just suppressing iTunes.

**Comment by tombonez** [comment]
Hi @bshaffer 👋🏻

This functionality is already available, see [Set replacement for iTunes / Apple Music](https://github.com/tombonez/noTunes?tab=readme-ov-file#set-replacement-for-itunes--apple-music) in the README.

Cheers,
Tom 🙂
