### ISSUE TITLE
Great app! Here is a screenshot to turn off iTunes

### ISSUE THREAD

**Issue by hankimlaw** [tombonez/noTunes#6]
Hello tombonez,

You deserve an award for this. I hated iTunes for interrupting my work.

Here is a screenshot of what it looks like when you turn on the noTunes app (menubar version) and block iTunes. 

I thought the screen shots would be helpful
The solid black circle is blocking iTunes. 
If the circle is clear, iTunes can pop up.

![Screen Shot 2020-11-11 at 4 48 09 PM](https://user-images.githubusercontent.com/64615207/98880931-b3053500-243d-11eb-9ebe-9fe1c3be651e.png)

![Screen Shot 2020-11-11 at 4 49 27 PM](https://user-images.githubusercontent.com/64615207/98881005-e21ba680-243d-11eb-96d4-72159b46cc6a.png)

**Comment by fehbari** [comment]
Thank you for this! Would be nice to have this info in the Readme (:

**Comment by tombonez** [comment]
@hankimlaw @fehbari

Thanks for the screenshots and feedback on this.

I'll be sure to get a couple screenshots on the README shortly.

I was hoping to get a new set of icons (app and menu bar) made before doing so, but that still hasn't happened ☹️

**Comment by benlc** [comment]
@tombonez how do I buy you a beer?

**Comment by francesco-cap** [comment]
@tombonez On my Mac the circles are white, so I think `full circle` and `empty circle` might be more accurate across the board. Thank you for building this!
![image](https://user-images.githubusercontent.com/70216848/107064171-14fcde80-6790-11eb-9dab-ce7fd9ecf204.png)
![image](https://user-images.githubusercontent.com/70216848/107064064-f26ac580-678f-11eb-9d5c-e9eb61c91c36.png)

**Comment by tombonez** [comment]
@benlc Haha, thanks! Appreciate the offer, but no beer necessary, just happy that you've found my little utility useful 🙂

@francesco-cap and everyone Thanks for the feedback, I'll update the README tomorrow with a simple user guide with screenshots.

I'll also give a friend of mine another nudge next week and see if he'll make a quick app and menubar icon set, as currently the icons don't really represent what the app does and were only ever supposed to be placeholders 👍

**Comment by tombonez** [comment]
Finally added screenshots and better app and menu bar icons.

Feel free to open up a pull request or another issue if you have any other suggestions 🙂
