### ISSUE TITLE
not working on mojave

### ISSUE THREAD

**Issue by koenige50** [tombonez/noTunes#8]
On Mac OS Mojave 10.14.6 the app launches but has no effect. iTunes still launches with media key presses, whatever state the menu button is in.
I tested with both the menu and non-menu versions.
Am I missing something?

**Comment by tombonez** [comment]
Hi @koenige50,

Looks like the bundleIdentifier and processName for iTunes was incorrect, this has now been fixed in version 2.3.

Any issues let me know.

Cheers,
Tom 🙂

**Comment by koenige50** [comment]
Seems to be working like a charm now. Much appreciated, thank you very much!
